//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetLog.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class : BaseEntity
    {
        public Class()
        {
            this.Methods = new HashSet<Method>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Namespace { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<Method> Methods { get; set; }
    }
}
