//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetLog.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log : BaseEntity
    {
        public int Id { get; set; }
        public int MethodId { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public int LogType { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Method Method { get; set; }
    }
}
