//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetLog.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Method : BaseEntity
    {
        public Method()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
